### ISSUE TITLE
a bit difficult for the sample

### ISSUE THREAD

**Issue by LazyScream** [KyoheiG3/GridView#3]
I'm new to Swift, but I don't know how to use samplecode. I don't know whether it's possible to give an example in a simpler way.
thx all !

**Comment by LazyScream** [comment]
I know how to use uitablevie
But the function I want to achieve is the Grid
I now get a new error
```swift
fatalError("could not dequeue a view of kind: \(T.className) with identifier \(identifier) - must register a nib or a class for the identifier")
```

**Comment by KyoheiG3** [comment]
@LazyScream There are various ways.
If you do on iOS11, Set `.never` to `contentInsetAdjustmentBehavior` which `GridView` has.

**Comment by LazyScream** [comment]
@KyoheiG3  thx all
But gridView.contentInsetAdjustmentBehavior = .never is not work 
I clearly stated that what I want to do is like the following video, but I'm not sure if the use of your library is complete, I am bothered

https://s3-ap-northeast-1.amazonaws.com/crackwatch/ScreenRecording_04-14-2018+02-00-56.MP4

**Comment by KyoheiG3** [comment]
It may not be possible to do exactly the same thing. But you can do something similar. GridView is not little bit smoother than it. because It is not `Image`. It has to layout for every scaling.
Have you looked `TimeTableViewController` of `GridViewExample` and did you try it?
<img width=300 src=https://user-images.githubusercontent.com/5707132/38752845-7f8e3290-3f97-11e8-9cea-f3188ddde68a.gif>

By the way, On iOS11, `UIScrollView` that is appended to `UIView` which has the `UIViewController` has top inset automatically, I think. If you want without it, append the `UIView` between `UIView` which has the `UIViewController` and `GridView` which you created.

**Comment by LazyScream** [comment]
I successfully produced the timetable I wanted based on your library, congratulations to me
https://s3-ap-northeast-1.amazonaws.com/crackwatch/success.mp4
The remaining small questions are, how do I make the screen's Label zoom in and out when I zoom?

**Comment by LazyScream** [comment]
UILabel I successfully completed the layout with the gesture zoom problem, but I found a bug in your library, I do not know if you are willing to correct for me
「Can't zoom when I scroll」 ！
I think the conflict has caused this problem，This problem is solved by solving my project，Thank you very much for your continued assistance
Hope to get your reply again before I find the answer，thx all !

**Comment by KyoheiG3** [comment]
If you want to scale, you can use `CGAffineTransform`.
https://developer.apple.com/documentation/coregraphics/cgaffinetransform

Scaling of the `GridView` is not a simple zooming, it has a re-layout. So zooming like `UIScrollView` is a bit difficult.
